//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APICommission
    {
        public int ID { get; set; }
        public int OperatorID { get; set; }
        public short APIID { get; set; }
        public decimal CommPer { get; set; }
        public decimal CommVal { get; set; }
        public decimal ChargePer { get; set; }
        public decimal ChargeVal { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime EditDate { get; set; }
        public bool Status { get; set; }
        public bool IsSlab { get; set; }
        public bool IsCircleSlab { get; set; }
    }
}
