//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankWithdrawal
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserDetails { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal Amount { get; set; }
        public decimal CommAmt { get; set; }
        public decimal ChargeAmt { get; set; }
        public decimal ClosingBalance { get; set; }
        public string PaymentType { get; set; }
        public int BankID { get; set; }
        public string BankName { get; set; }
        public string HolderName { get; set; }
        public string Account { get; set; }
        public string IfscCode { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string Remarks { get; set; }
    }
}
