//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeMoneyTran
    {
        public int ID { get; set; }
        public Nullable<decimal> AmountStart { get; set; }
        public Nullable<decimal> AmountEnd { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string IsFlat { get; set; }
        public Nullable<int> UserID { get; set; }
        public int SchemeID { get; set; }
    }
}
