//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CircleAPISetting
    {
        public int ID { get; set; }
        public int CircleID { get; set; }
        public int OperatorID { get; set; }
        public short APIID { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsActive { get; set; }
        public decimal AmountLimit { get; set; }
        public int APIID1 { get; set; }
        public short APIID2 { get; set; }
        public short APIID3 { get; set; }
        public short APIID4 { get; set; }
        public short APIID5 { get; set; }
        public short APIID6 { get; set; }
        public int APICnt { get; set; }
    }
}
