//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int ID { get; set; }
        public int OperatorID { get; set; }
        public int UserID { get; set; }
        public short ApiID { get; set; }
        public decimal CommPer { get; set; }
        public decimal CommVal { get; set; }
        public decimal ServiceChargePer { get; set; }
        public decimal ServiceChargeVal { get; set; }
        public System.DateTime AddDate { get; set; }
        public int SchemeID { get; set; }
        public bool IsActive { get; set; }
    }
}
