//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int ID { get; set; }
        public int ParameterTypeId { get; set; }
        public string EmailType { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public bool IsActive { get; set; }
    }
}
