//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailApi
    {
        public int ID { get; set; }
        public string SMTPName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
        public string SmtpHost { get; set; }
        public int UserID { get; set; }
    }
}
