//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorTransaction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public long TxnID { get; set; }
        public string Number { get; set; }
        public string Status { get; set; }
        public string OPTRef { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
    }
}
