//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCTransaction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string CardNumber { get; set; }
        public string RefNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string ContactNo { get; set; }
        public string MailID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Status { get; set; }
        public long RefID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
    }
}
