//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantActivation
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string ClientID { get; set; }
        public string MobileNo { get; set; }
        public string MerchantName { get; set; }
        public string PanNumber { get; set; }
        public int PinCode { get; set; }
        public string StateName { get; set; }
        public string District { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public string Document3 { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime EditDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string UpdateBy { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
    }
}
