//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPOSTransaction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public long RefID { get; set; }
        public string Status { get; set; }
        public string Number { get; set; }
        public string EmailID { get; set; }
        public string Reason { get; set; }
        public string Username { get; set; }
        public System.DateTime AddDate { get; set; }
        public string TransactionID { get; set; }
        public string DeviceID { get; set; }
        public decimal Amount { get; set; }
        public string CustomerName { get; set; }
        public string TxnID { get; set; }
        public string CardType { get; set; }
        public string PaymentMode { get; set; }
        public string RRN { get; set; }
        public string SettlementStatus { get; set; }
        public string ReceiptUrl { get; set; }
        public string OrderNo { get; set; }
        public string ReverseReferenceNumber { get; set; }
        public string MessageCode { get; set; }
        public string ExternalRefNumber { get; set; }
        public string FormattedPan { get; set; }
        public string MerchantName { get; set; }
        public string MID { get; set; }
        public string PaymentCardBrand { get; set; }
        public string StatusAuth { get; set; }
        public string TID { get; set; }
        public string TxnType { get; set; }
        public string UserAgreement { get; set; }
        public string ChargeSlipDate { get; set; }
        public string ReadableChargeSlipDate { get; set; }
        public string CardTxnTypeDesc { get; set; }
        public string DxMode { get; set; }
        public string AcquirerCode { get; set; }
        public string CreatedTime { get; set; }
    }
}
