//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWalletOperatorCode
    {
        public int Id { get; set; }
        public string ProviderName { get; set; }
        public string CircleName { get; set; }
        public short APIID { get; set; }
        public string OpCode { get; set; }
        public string City { get; set; }
        public string MNCCode { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsActive { get; set; }
    }
}
