//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public int ID { get; set; }
        public string OperatorName { get; set; }
        public short ServiceID { get; set; }
        public string Status { get; set; }
        public string ApiCode { get; set; }
        public string APIOperatorCode { get; set; }
        public string OperatorType { get; set; }
        public string ImageUrl { get; set; }
        public bool IsBBPS { get; set; }
        public bool IsValidate { get; set; }
        public bool IsPartial { get; set; }
        public decimal MinAmount { get; set; }
        public decimal MaxAmount { get; set; }
        public int MainMinLength { get; set; }
        public int MainMaxLength { get; set; }
        public string APIOperatorCode1 { get; set; }
        public string APIOperatorCode2 { get; set; }
        public string APIOperatorCode3 { get; set; }
        public string APIOperatorCode4 { get; set; }
        public string APIOperatorCode5 { get; set; }
        public string APIOperatorCode6 { get; set; }
        public string APIOperatorCode7 { get; set; }
        public string APIOperatorCode8 { get; set; }
        public string APIOperatorCode9 { get; set; }
        public string APIOperatorCode10 { get; set; }
        public string APIOperatorCode11 { get; set; }
        public string AmountPlans { get; set; }
        public string AllowType { get; set; }
        public bool IsRandom { get; set; }
        public string APIOperatorCode12 { get; set; }
        public string APIOperatorCode13 { get; set; }
        public string APIOperatorCode14 { get; set; }
        public string APIOperatorCode15 { get; set; }
        public string APIOperatorCode16 { get; set; }
        public string APIOperatorCode17 { get; set; }
        public string APIOperatorCode18 { get; set; }
        public string APIOperatorCode19 { get; set; }
        public string APIOperatorCode20 { get; set; }
        public string APIOperatorCode21 { get; set; }
        public string APIOperatorCode22 { get; set; }
        public string APIOperatorCode23 { get; set; }
        public string APIOperatorCode24 { get; set; }
        public string APIOperatorCode25 { get; set; }
        public string RejectedAmount { get; set; }
        public string BBPSCode { get; set; }
        public Nullable<int> StateName { get; set; }
        public string APIOperatorCode26 { get; set; }
        public string APIOperatorCode27 { get; set; }
        public string APIOperatorCode28 { get; set; }
        public string APIOperatorCode29 { get; set; }
        public string APIOperatorCode30 { get; set; }
        public string APIOperatorCode31 { get; set; }
        public string APIOperatorCode32 { get; set; }
        public string APIOperatorCode33 { get; set; }
        public string APIOperatorCode34 { get; set; }
        public string APIOperatorCode35 { get; set; }
        public string APIOperatorCode36 { get; set; }
        public string APIOperatorCode37 { get; set; }
        public string APIOperatorCode38 { get; set; }
        public string APIOperatorCode39 { get; set; }
        public string APIOperatorCode40 { get; set; }
    }
}
