//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorSwitching
    {
        public int ID { get; set; }
        public int OperatorID { get; set; }
        public int APICnt { get; set; }
        public bool IsActive { get; set; }
        public short API1 { get; set; }
        public short API2 { get; set; }
        public short API3 { get; set; }
        public short API4 { get; set; }
        public short API5 { get; set; }
        public short API6 { get; set; }
        public short API7 { get; set; }
        public int UserID { get; set; }
    }
}
