//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public int BankID { get; set; }
        public string ChequeDDNo { get; set; }
        public Nullable<System.DateTime> ChequeDDDate { get; set; }
        public string RefNumber { get; set; }
        public string DocumentUrl { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string AccountDetails { get; set; }
        public string UpdatedBy { get; set; }
    }
}
