//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoutRecipient
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string AccountNo { get; set; }
        public string IFSC { get; set; }
        public string BankName { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Status { get; set; }
        public bool IsValidate { get; set; }
        public string CFBeneID { get; set; }
        public string CFStatus { get; set; }
    }
}
