//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinCode
    {
        public int Id { get; set; }
        public Nullable<double> PinCode1 { get; set; }
        public string DivisionName { get; set; }
        public string RegionName { get; set; }
        public string CircleName { get; set; }
        public string Taluk { get; set; }
        public string DistrictName { get; set; }
        public string StateName { get; set; }
    }
}
