//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public short ID { get; set; }
        public string ServiceName { get; set; }
        public bool IsActive { get; set; }
        public bool IsBBPS { get; set; }
        public bool IsAuth { get; set; }
        public string ImageUrl { get; set; }
        public short CategoryID { get; set; }
    }
}
