//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesParameter
    {
        public int Id { get; set; }
        public string MsgType { get; set; }
        public string Parameter { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
