//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string SupportType { get; set; }
        public string Message { get; set; }
        public string TranId { get; set; }
        public string Status { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string Attachment { get; set; }
        public string UpdatedBy { get; set; }
        public string APIStatus { get; set; }
    }
}
