//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Usertype { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool Status { get; set; }
        public string OwnerName { get; set; }
        public string FirmName { get; set; }
        public string AltNo { get; set; }
        public string Address { get; set; }
        public string IP { get; set; }
        public string ApiKey { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CallBackurl { get; set; }
        public int SchemeID { get; set; }
        public string OtcRef { get; set; }
        public Nullable<System.DateTime> OtcDate { get; set; }
        public decimal CapBalance { get; set; }
        public string AgentID { get; set; }
        public string AepsCallBackurl { get; set; }
        public int AepsLimit { get; set; }
        public decimal CapBalances { get; set; }
        public decimal AEPSBalance { get; set; }
        public string GSTNumber { get; set; }
        public string EmailID { get; set; }
        public string AepsInquiryUrl { get; set; }
        public string AepsTransactionUrl { get; set; }
        public string AepsTheme { get; set; }
        public string AepsReferrerUrl { get; set; }
        public string SDKPassword { get; set; }
        public decimal DayLimit { get; set; }
        public decimal DayUsage { get; set; }
        public System.DateTime DayLimitUpdate { get; set; }
        public bool IsDayLimitActive { get; set; }
        public string BBPSTransactionURL { get; set; }
        public string PanTransactionURL { get; set; }
        public string PanVerificationURL { get; set; }
        public string PaymentURL { get; set; }
        public string VirtualAccountNo { get; set; }
        public bool IsAllowVirtualCredit { get; set; }
        public string MATMTransactionURL { get; set; }
        public bool IsCircleSwitching { get; set; }
        public int AffiliateUserID { get; set; }
        public string AvenuesAgentID { get; set; }
        public string AffiliateType { get; set; }
        public Nullable<decimal> AffiliateValue { get; set; }
        public string ReferralCode { get; set; }
        public string PancardNo { get; set; }
        public string AadharNo { get; set; }
        public string PinCode { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string WebsiteUrl { get; set; }
        public string ProfileImageUrl { get; set; }
        public string CINNo { get; set; }
        public string CompanyType { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public string Reason { get; set; }
        public string KYCStatus { get; set; }
        public Nullable<System.DateTime> KYCRequestDate { get; set; }
        public Nullable<System.DateTime> KYCResponseDate { get; set; }
        public string KYCRemarks { get; set; }
        public string OfficeAddress { get; set; }
        public string BusinessType { get; set; }
    }
}
