//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualAccountNoCollect
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string APIName { get; set; }
        public string AccountId { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string GSTIN { get; set; }
        public string CustomerID { get; set; }
        public string AccountNo { get; set; }
        public string IfscCode { get; set; }
        public string AccountType { get; set; }
        public string VirtualAccountNumber { get; set; }
        public string VirtualIfscCode { get; set; }
        public string AcName { get; set; }
        public string BankName { get; set; }
        public string AcRefID { get; set; }
        public string APIRefID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifyOn { get; set; }
        public string ModifyBy { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
    }
}
