//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServices.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessServices.Resource.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient is not verified..
        /// </summary>
        internal static string BenenotVerify {
            get {
                return ResourceManager.GetString("BenenotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong from operator end..
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found.
        /// </summary>
        internal static string Datanotfound {
            get {
                return ResourceManager.GetString("Datanotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient deleted successfully..
        /// </summary>
        internal static string DeleRpnt {
            get {
                return ResourceManager.GetString("DeleRpnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, contact to administrator..
        /// </summary>
        internal static string Errorsm {
            get {
                return ResourceManager.GetString("Errorsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Fd {
            get {
                return ResourceManager.GetString("Fd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        internal static string InavlidToken {
            get {
                return ResourceManager.GetString("InavlidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IFSC Format..
        /// </summary>
        internal static string InifscFromat {
            get {
                return ResourceManager.GetString("InifscFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account number format..
        /// </summary>
        internal static string InvalidAcFormat {
            get {
                return ResourceManager.GetString("InvalidAcFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipient Id..
        /// </summary>
        internal static string InvalidBene {
            get {
                return ResourceManager.GetString("InvalidBene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ifsc code..
        /// </summary>
        internal static string InvalidIfsc {
            get {
                return ResourceManager.GetString("InvalidIfsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address..
        /// </summary>
        internal static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number format..
        /// </summary>
        internal static string InvalidMNofrmt {
            get {
                return ResourceManager.GetString("InvalidMNofrmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Message..
        /// </summary>
        internal static string InvalidMsg {
            get {
                return ResourceManager.GetString("InvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name format..
        /// </summary>
        internal static string InvalidNamefrmt {
            get {
                return ResourceManager.GetString("InvalidNamefrmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid otp..
        /// </summary>
        internal static string InvalidOtp {
            get {
                return ResourceManager.GetString("InvalidOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OurCode..
        /// </summary>
        internal static string InvalidOurcode {
            get {
                return ResourceManager.GetString("InvalidOurcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rimitter Id..
        /// </summary>
        internal static string InvalidRemitterId {
            get {
                return ResourceManager.GetString("InvalidRemitterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction ID..
        /// </summary>
        internal static string InvalidTxnID {
            get {
                return ResourceManager.GetString("InvalidTxnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your limit is reached..
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number already exists. Try with another mobile number..
        /// </summary>
        internal static string Mobilenoexist {
            get {
                return ResourceManager.GetString("Mobilenoexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Plans Found with this Amount..
        /// </summary>
        internal static string NoPlanFound {
            get {
                return ResourceManager.GetString("NoPlanFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is expired..
        /// </summary>
        internal static string OtpExpired {
            get {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent on mobile number..
        /// </summary>
        internal static string OTPSend {
            get {
                return ResourceManager.GetString("OTPSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pd {
            get {
                return ResourceManager.GetString("Pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient added successfully..
        /// </summary>
        internal static string RecipientAddSu {
            get {
                return ResourceManager.GetString("RecipientAddSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Id is already present..
        /// </summary>
        internal static string RecipientExist {
            get {
                return ResourceManager.GetString("RecipientExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient name should be min. 5 letter..
        /// </summary>
        internal static string RecipientNameLength {
            get {
                return ResourceManager.GetString("RecipientNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitter added successfully..
        /// </summary>
        internal static string remitteradded {
            get {
                return ResourceManager.GetString("remitteradded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitter mobile number not exist..
        /// </summary>
        internal static string Remitternotexist {
            get {
                return ResourceManager.GetString("Remitternotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted successfully..
        /// </summary>
        internal static string RequestAccpted {
            get {
                return ResourceManager.GetString("RequestAccpted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient verifyed successfully..
        /// </summary>
        internal static string Rpntverifysu {
            get {
                return ResourceManager.GetString("Rpntverifysu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender mobile number already exist..
        /// </summary>
        internal static string SenderExist {
            get {
                return ResourceManager.GetString("SenderExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitter name should be min. 5 letter..
        /// </summary>
        internal static string SenderNameLength {
            get {
                return ResourceManager.GetString("SenderNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is temporary down..
        /// </summary>
        internal static string ServiceDown {
            get {
                return ResourceManager.GetString("ServiceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to use this service Contact Administrator..
        /// </summary>
        internal static string ServiceNotAuth {
            get {
                return ResourceManager.GetString("ServiceNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Su {
            get {
                return ResourceManager.GetString("Su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket already exist..
        /// </summary>
        internal static string Ticketexist {
            get {
                return ResourceManager.GetString("Ticketexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your token is expired..
        /// </summary>
        internal static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trigger called successfully..
        /// </summary>
        internal static string TriggerCallSu {
            get {
                return ResourceManager.GetString("TriggerCallSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ref already exist..
        /// </summary>
        internal static string TxnAlreadyexist {
            get {
                return ResourceManager.GetString("TxnAlreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction amount was already credited to your wallet..
        /// </summary>
        internal static string TxnAmountAlredycredit {
            get {
                return ResourceManager.GetString("TxnAmountAlredycredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found..
        /// </summary>
        internal static string TxnNotFound {
            get {
                return ResourceManager.GetString("TxnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is not pending mode..
        /// </summary>
        internal static string TxnNtPending {
            get {
                return ResourceManager.GetString("TxnNtPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is pending mode..
        /// </summary>
        internal static string TxnPending {
            get {
                return ResourceManager.GetString("TxnPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When done the transaction then you can check the transaction status after 5 minutes..
        /// </summary>
        internal static string TxnStatusCheckBlock {
            get {
                return ResourceManager.GetString("TxnStatusCheckBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction success..
        /// </summary>
        internal static string TxnSu {
            get {
                return ResourceManager.GetString("TxnSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Successful..
        /// </summary>
        internal static string Txnsuccess {
            get {
                return ResourceManager.GetString("Txnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown response..
        /// </summary>
        internal static string Unknownresponse {
            get {
                return ResourceManager.GetString("Unknownresponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is suspended..
        /// </summary>
        internal static string Youracsuspend {
            get {
                return ResourceManager.GetString("Youracsuspend", resourceCulture);
            }
        }
    }
}
